name: Run tests

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "~1.21"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Unit Test
        run: go test -coverprofile cover.out ./...
