name: Run tests

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "~1.21"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Unit Test
        run: go test -coverprofile cover.out ./...
